env:
    global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "EsAos9ygqYkxMomz2mI9crMl1Wty21+8YsE6ehHb8XmTcs8IiLSQJzLouz27NjZuIBtEfVgNweIJ4qhizNFjBN7mbb0mFNGzPVsPijh1ew9AufPy9WCrtAfKllxTAEANUehA7PokzuZcAefnZuzzSxrXke3MQp0lNoMqPYus8Rk="
    matrix:
        - BUILD_SYSTEM=cmake


addons:
  coverity_scan:
    project:
        name: "jwright85/cse531"
        description: "CSE531 User Threads"
    notification_email: jeremy@quiescent.us
    build_command_prepend: cmake ..
    build_command:   cmake --build .
    branch_pattern: coverity_scan


language: cpp
compiler:
- gcc
before_install:
 # g++4.8.1
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
 # g++4.8.1
 - sudo apt-get install -qq g++-4.8
 - export CXX="g++-4.8"

script: 
    - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then
        case $BUILD_SYSTEM in
            cmake)
            cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/_install &&
            cmake --build .
            ;;
        fi

after_script:
    - ctest -V .
